server:
  port: 8083
spring:

  application:
    name: fake-payment-provider
  flyway:
    user: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
    locations: classpath:db/migration
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
logging:
  level:
    root: info